# Built by hand rather than left to Railway's auto-detection, for one reason:
# PGlite is Postgres compiled to wasm, and its .wasm, .data and pg_trgm.tar.gz
# have to exist on disk at RUNTIME. next.config.js deliberately tells Next not
# to bundle them (`serverExternalPackages`), because bundling mangles their
# paths and the server then cannot start at all. A builder that ships only
# Next's traced output therefore drops exactly the files the database is made
# of — and does it silently, producing an image that builds green and dies on
# the first request.
#
# So: no `output: 'standalone'`, no pruning. node_modules ships whole.

# ── deps: bun installs, because bun.lock is the lockfile that was tested ──
# Resolving the tree with npm instead would produce a DIFFERENT set of
# versions from the one the test suite ran against, which is the one thing a
# lockfile exists to prevent.
FROM oven/bun:1.3.14 AS deps
WORKDIR /app
# Manifests only, so this layer is reused on every push that does not change
# a dependency — which is most of them.
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# ── build and run on Node, not on Bun ──────────────────────────────────────
# Next's production server targets Node; Bun can usually run it, but "usually"
# is not what this deployment is for, and PGlite's wasm loading is exactly the
# kind of thing that differs between runtimes. Bun resolves the tree, Node
# runs it. The output of `bun install` is an ordinary node_modules directory,
# so nothing about this is unusual.
FROM node:22-slim AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# devDependencies are required here — typescript and the Next plugin are not
# optional at build time. No database is reachable during a build and none is
# needed: every route that touches PGlite is dynamic, so nothing is
# prerendered against it.
# Invoked through Node against next's own entry file rather than through
# node_modules/.bin/next: that shim is generated by whichever package manager
# installed the tree, and this tree was installed by bun, which is not present
# in this stage. The file below is what the shim points at either way.
RUN node node_modules/next/dist/bin/next build

FROM node:22-slim AS runtime
WORKDIR /app
ENV NODE_ENV=production
# Where the PGlite directory lives. It MUST point inside the mounted volume,
# or the database is recreated empty on every deploy and every conversation is
# lost. The lock file lands beside it at /data/minddyte.lock — also on the
# volume, which is what lets one container see that another still holds it.
ENV MINDDYTE_DATA_DIR=/data/minddyte

# No `public/` copy: this project has none. Every asset is either imported
# through the bundler or drawn inline as SVG, so there is nothing to serve
# from disk — and COPYing a directory that does not exist fails the build.
COPY --from=deps  /app/node_modules   ./node_modules
COPY --from=build /app/.next          ./.next
COPY --from=build /app/package.json   ./package.json
COPY --from=build /app/next.config.js ./next.config.js

# db/bootstrap.ts reads these .sql files off disk at RUNTIME, from
# process.cwd(), the first time it meets an empty data directory — which on a
# fresh volume is the very first request. They are data, not code, so the
# bundler never sees them and shipping .next alone leaves the app unable to
# create its own schema. Found by running the image, not by reading it.
COPY --from=build /app/db/migrations  ./db/migrations

# Railway assigns the port. Binding 3000 by hand makes the service
# unreachable however healthy it is, and 0.0.0.0 is needed because localhost
# inside a container is reachable only from inside it.
#
# `exec` matters more than it looks: without it the shell stays as pid 1 and
# SIGTERM never reaches Next, so the lock is not released on shutdown and the
# next container waits out the full 30-second lease on EVERY deploy.
EXPOSE 3000
CMD ["sh", "-c", "exec node node_modules/next/dist/bin/next start -H 0.0.0.0 -p ${PORT:-3000}"]
