/**
 * Appended to the system prompt ONLY on a turn that asks for a diagram
 * (spec §3). The library it documents is src/scene/runtime/lib.ts; a name
 * changed there must change here.
 */
export const DIAGRAM_GUIDE = [
  '## Interactive diagrams',
  '',
  'When a picture would genuinely help (the user asked to see, visualize, animate, draw or illustrate something, or wrote /visualize), add ONE interactive diagram (two at most) to your answer as a fenced code block whose info string is exactly `scene`. Explain in words as well: the diagram supports the answer, it does not replace it. Never use a scene block for anything else.',
  '',
  'The block is plain JavaScript that describes the scene with the functions below. Nothing else exists: no DOM, no network, no imports, no console. Keep it under 60 lines. Scene units: x from -8 to 8, y from -4.5 to 4.5, y points up, origin at the centre.',
  '',
  'Shapes (created hidden; show them with play):',
  '- axes({ x: [min, max], y: [min, max] }) -> a coordinate system filling the view. Methods: .plot(x => ..., { color }), .point([x, y], { color }), .vector([x, y], { color }) (from the origin), .label(text, [x, y], { color }).',
  '- grid({ x: [min, max], y: [min, max] }) -> a unit grid. Methods: .vector([x, y], { color }); .applyMatrix([[a, b], [c, d]]) -> an animation that transforms the grid and its vectors.',
  '- vector([x, y], { color }), point([x, y], { color }), label(text, [x, y], { color, size, tex }). Labels are LaTeX by default ("\\\\sin x"); pass { tex: false } for plain words.',
  '- array([values]) -> boxes in a row. Animations: .swap(i, j), .highlight(i, color) (color null clears), .set(i, value).',
  '- tree({ label, children: [...] }) and graph([ids], [[from, to], ...]) -> nodes and edges; a node is named by its label (or its id). Animations: .visit(name, color), .edge(from, to, color).',
  '- lanes([names]) -> horizontal queues or partitions. Animations: .send(label, laneIndex, color), .consume(laneIndex).',
  '',
  'Animation (each play() is one step; the viewer can pause and scrub):',
  '- play(anim, anim, ...) runs animations together. play(obj) is short for play(create(obj)).',
  '- create(obj) draws it; fadeOut(obj); move(obj, [dx, dy]); transform(a, b) turns a into the shape of b (b itself is never shown); wait(seconds).',
  '- caption(text) sets the narration shown for the next play(); title(text) names the diagram.',
  '',
  'Knobs: const k = slider("name", min, max, initial, step) returns the current value. When the user moves it, the whole code runs again with the new value, so compute everything from it.',
  '',
  'Also available: PI, TAU, E, sin, cos, tan, asin, acos, atan, atan2, sqrt, abs, exp, log, pow, min, max, floor, ceil, round, sign, hypot; colours BLUE, TEAL, GREEN, YELLOW, GOLD, RED, PURPLE, WHITE, GREY.',
  '',
  'Limits: at most 400 shapes, 60 play() steps and 8 sliders.',
  '',
  'Example 1:',
  '```scene',
  'title("Frequency squeezes a sine wave")',
  'const k = slider("k", 1, 5, 2, 0.5)',
  'const ax = axes({ x: [-PI, PI], y: [-1.5, 1.5] })',
  'play(create(ax))',
  'caption("y = sin(kx): a larger k packs more waves into the same width")',
  'play(create(ax.plot(x => sin(k * x), { color: BLUE })))',
  '```',
  '',
  'Example 2:',
  '```scene',
  'title("Bubble sort")',
  'const values = [5, 2, 8, 1, 4]',
  'const a = array(values)',
  'play(create(a))',
  'for (let end = values.length - 1; end > 0; end--) {',
  '  for (let i = 0; i < end; i++) {',
  '    caption(`Compare ${values[i]} and ${values[i + 1]}`)',
  '    play(a.highlight(i, YELLOW), a.highlight(i + 1, YELLOW))',
  '    if (values[i] > values[i + 1]) {',
  '      ;[values[i], values[i + 1]] = [values[i + 1], values[i]]',
  '      play(a.swap(i, i + 1))',
  '    }',
  '    play(a.highlight(i, null), a.highlight(i + 1, null))',
  '  }',
  '}',
  '```',
].join('\n')
